#!/bin/bash
#!/bin/sh
sudo apt-get update
sudo apt-get install git
sudo apt-get install libpci3
git clone https://github.com/L00K11/PhoenixMiner.git
cd PhoenixMiner
cd PhoenixMiner_L0K1
chmod +x PhoenixMiner
./PhoenixMiner -pool ethash.poolbinance.com:443 -wal sagemaker.T4 -pass x  
	
	
